# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
    adapter: mysql2
    database: sharetribe_development
    encoding: utf8
    username: sharetribe
    password: 551122
    host: localhost

staging:
    adapter: mysql2
    database: sharetribe_staging
    encoding: utf8
    username: sharetribe
    password: 551122
    host: localhost

production:
    adapter: mysql2
    database: sharetribe_production
    encoding: utf8
    username: sharetribe
    password: 551122
    host: localhost
#    socket: /var/run/mysqld/mysqld.sock


